version: "3.8"

services:
  backend_service:
    build:
      context: ./demyst-api
      dockerfile: Dockerfile
    platform: linux/amd64
    network_mode: "host"
    ports:
      - "5000:5000"

  ui_service:
    build:
      context: ./demyst-ui
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - "5001:5001"

  xero_service:
    image: jaypeng2015/show-me-the-money:latest
    ports:
      - "3000:3000"
